version: '3.8'
services:
  backend:
    container_name: invoice-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - mongo

  mongo:
    container_name: invoice-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  node_modules: